export const RITUAL_TYPE_SEEDS = [
  {
    slug: "purification",
    name: "Очищение",
    type: "light",
    requiredComponents: ["травы"],
    energyCost: 20,
    duration: "безграничное",
    successRate: 100,
  },
  {
    slug: "consecration",
    name: "Освящение",
    type: "light",
    requiredComponents: ["святая вода"],
    energyCost: 22,
    duration: "45 минут",
    successRate: 98,
  },
  {
    slug: "blessing",
    name: "Благословение",
    type: "light",
    requiredComponents: ["трава"],
    energyCost: 15,
    duration: "20 минут",
    successRate: 100,
  },
  {
    slug: "weaving",
    name: "Тканье",
    type: "harmony",
    requiredComponents: ["трава"],
    energyCost: 18,
    duration: "навсегда",
    successRate: 100,
  },
  {
    slug: "coition",
    name: "Соитие",
    type: "light",
    requiredComponents: ["трава"],
    energyCost: 66,
    duration: "10 минут",
    successRate: 100,
  },
  {
    slug: "offer",
    name: "Предложение",
    type: "light",
    requiredComponents: ["трава"],
    energyCost: 66,
    duration: "Контракт 3 года",
    successRate: 100,
  },
] as const;
